<?php
include_once('functions.inc.php');

$a_buffer="";
$sql_buffer="";
$error_message="";

// Check if installation was already completed
$tables_exist = false;
$config_exists = file_exists('../include/config.inc.php');

$db_check = new DB_Sql();
$db_check->Halt_On_Error = 'no';
$db_check->Database = $db_name;
$db_check->Host = $db_host;
$db_check->User = $db_user;
$db_check->Password = $db_password;
if($db_check->connect()) {
    // Check if tables already exist
    $db_check->query("SHOW TABLES LIKE '{$db_prefix}auth'");
    if($db_check->num_rows() > 0) {
        $tables_exist = true;
        $error_message .= 'Installation already completed! Tables already exist.<br>';
        if ($config_exists) {
            $error_message .= 'If you want to reinstall, please drop the existing tables first.<br>';
        } else {
            $error_message .= 'Config file missing - will be recreated, but tables exist.<br>';
        }
    }
}

// Generate .env file instead of config.inc.php
$http_root = str_replace('/install', '', dirname($PHP_SELF));
$current_date = date('Y-m-d H:i:s');

// Generate secure key
function generate_secure_key() {
    if (function_exists('random_bytes')) {
        try {
            return base64_encode(random_bytes(32));
        } catch (Exception $e) {
            // Fallback wenn random_bytes fehlschlägt
        }
    }
    
    // Fallback für ältere PHP-Versionen
    $bytes = '';
    for ($i = 0; $i < 32; $i++) {
        $bytes .= chr(mt_rand(0, 255));
    }
    return base64_encode($bytes);
}

$secure_key = generate_secure_key();

// Create .env content
$env_content = <<<EOT
# TimeEffect Environment Configuration
# Generated by installation on: {$current_date}

# Database Configuration
DB_HOST={$db_host}
DB_DATABASE={$db_name}
DB_USERNAME={$db_user}
DB_PASSWORD={$db_password}
DB_PREFIX={$db_prefix}

# Application Settings
APP_ENV=production
APP_DEBUG=false
APP_HTTP_ROOT={$http_root}
APP_ROOT_PATH={$_SERVER['DOCUMENT_ROOT']}{$http_root}
APP_LANGUAGE={$interface_language}

# Formatting Settings
DECIMAL_POINT={$decimal_point}
THOUSANDS_SEPARATOR={$thousands_seperator}
CURRENCY={$currency}

# Session Configuration
SESSION_LIFETIME={$session_length}
SESSION_SECURE=false

# User Registration Settings
ALLOW_REGISTRATION={$allow_registration}
REGISTRATION_EMAIL_CONFIRM={$registration_email_confirm}
ALLOW_PASSWORD_RECOVERY={$allow_password_recovery}
REGISTRATION_SECURE_DEFAULTS={$registration_secure_defaults}
REGISTRATION_DEFAULT_ACCESS={$registration_default_access}

# Other Settings
ALLOW_DELETE={$allow_delete}

# Security
APP_KEY=base64:{$secure_key}

EOT;

// Write .env file
if (file_put_contents('../.env', $env_content)) {
    // Success - .env created
} else {
    $error_message .= 'opening of file \'.env\' for writing failed!<br>';
}

// Check if we should stop installation (only if tables exist AND config exists)
if(!empty($error_message) && $tables_exist && $config_exists) {
?>
				<b>TIMEEFFECT Installation - failed!</b><br><br>
				<span class="errorMessage"><b>ERROR(S): <?php if(isset($error_message)) echo $error_message; ?></b></span><br>
<?php
	return;
} elseif (!empty($error_message)) {
	// Show warning but continue if only tables exist (config will be recreated)
?>
				<b>TIMEEFFECT Installation - Warning</b><br><br>
				<span class="warning"><b>WARNING: <?php if(isset($error_message)) echo $error_message; ?></b></span><br>
				<span style="color: green;"><b>Continuing with config file creation...</b></span><br><br>
<?php
}

// Only create tables if they don't exist yet
if (!$tables_exist && $sql_file = @fopen('timeeffect.sql', 'r')) {
	while(!feof($sql_file)) {
		$sql_buffer .= fread($sql_file, 4096);
	}
	@fclose($sql_file);
	$sql_buffer = str_replace('<%db_prefix%>', $db_prefix, $sql_buffer);
	$sql_buffer = str_replace('<%admin_user%>', $admin_user, $sql_buffer);
	$sql_buffer = str_replace('<%admin_password%>', md5($admin_password), $sql_buffer);

	$pieces = array();
	splitSqlFile($pieces, $sql_buffer, 0);
	$pieces_count = count($pieces);
	for($i = 0; $i < $pieces_count; $i++) {
		$db->query($pieces[$i]);
		if($db->Errno) {
			$error_message .= 'execution of SQL command failed (' . $pieces[$i] . ')<br>';
			break;
		}
	}
} else {
	$error_message .= 'opening of file \'timeeffect.sql\' failed!<br>';
}

if ($tables_exist) {
	// Tables already exist, skip SQL execution
	echo "<span style='color: orange;'><b>Tables already exist - skipping SQL execution</b></span><br><br>";
}

if(!empty($error_message)) {
?>
				<b>TIMEEFFECT Installation - failed!</b><br><br>
				<span class="errorMessage"><b>ERROR(S): <?php if(isset($error_message)) echo $error_message; ?></b></span><br>
<?php
	return;
}
?>
				<b>TIMEEFFECT Installation - finished</b><br><br>
				The installation process has been successfully finished.<br><br>
				
				<b>IMPORTANT: Complete the following steps to finalize your installation:</b><br><br>
				
				<b>Step 1: Install Composer Dependencies</b><br>
				Run the following commands in your terminal:<br>
				<code style="background: #f0f0f0; padding: 5px; display: block; margin: 5px 0;">
				# Navigate to your TimeEffect directory<br>
				cd <?php echo $_SERVER['DOCUMENT_ROOT'] . str_replace('/install', '', dirname($_SERVER['PHP_SELF'])); ?><br><br>
				# Install dependencies<br>
				composer install --no-dev --optimize-autoloader
				</code><br>
				
				<b>Step 2: Configuration Complete</b><br>
				✅ Your .env configuration file has been automatically generated!<br>
				<code style="background: #f0f0f0; padding: 5px; display: block; margin: 5px 0;">
				# Review your .env file if needed<br>
				nano .env
				</code><br>
				
				<b>Step 3: Security & Permissions</b><br>
				• Remove the 'install' directory for security reasons<br>
				• Set '.env' file permissions to read-only (600) for security<br>
				• Set 'include/pdflayout.inc.php' to writeable for your web server process<br><br>
				
				After completing these steps, you can access your TIMEEFFECT installation <a href="../index.php"><b>>> here</b></a>;
